package hibernate.model.org;

// Generated Feb 18, 2016 2:20:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Robot generated by hbm2java
 */
@Entity
@Table(name = "robot", schema = "public")
public class Robot implements java.io.Serializable {

	private int robotid;
	private String robotname;
	private Double robotprice;

	public Robot() {
	}

	public Robot(int robotid) {
		this.robotid = robotid;
	}

	public Robot(int robotid, String robotname, Double robotprice) {
		this.robotid = robotid;
		this.robotname = robotname;
		this.robotprice = robotprice;
	}

	@Id
	@Column(name = "robotid", unique = true, nullable = false)
	public int getRobotid() {
		return this.robotid;
	}

	public void setRobotid(int robotid) {
		this.robotid = robotid;
	}

	@Column(name = "robotname")
	public String getRobotname() {
		return this.robotname;
	}

	public void setRobotname(String robotname) {
		this.robotname = robotname;
	}

	@Column(name = "robotprice", precision = 17, scale = 17)
	public Double getRobotprice() {
		return this.robotprice;
	}

	public void setRobotprice(Double robotprice) {
		this.robotprice = robotprice;
	}

}
